# Base image for ipp integration tests to avoid duplication of the same code in multiple Dockerfiles.
# phil927/zgrab_ipp_service_base is built from this
FROM zgrab2_service_base:latest

RUN apt-get install -y \
  cups \
  cups-pdf